2012/03/06 (v.1.9)

diff --git a/check_cciss b/check_cciss
--- a/check_cciss
+++ b/check_cciss
@@ -13,24 +13,28 @@
 # (Array, controller, cache, battery, etc...)
 #
 #
-# Usage: ./check_cciss [-v] [-d] [-e <number>] [-E <name>]
+# Usage: ./check_cciss [-v] [-p] [-e <number>] [-E <name>] [-s] [-d]
 #
-#  -v                   = output status and informations about RAID
+#  -v                   = show status and informations about RAID
+#  -p                   = show detail for physical drives
 #  -e <number>          = exclude slot number
 #  -E <name>            = exclude chassis name
-#  -d                   = use for debug ( command line mode )
+#  -s                   = detect controller with HPSA driver (Hewlett Packard Smart Array)
+#  -d                   = use for debug (command line mode)
+#  -h                   = help information
+#  -V                   = version information
 #
 #
 # !!!!!! NOTE: !!!!!!
 #
-# HP Array Configuration Utility CLI (hpacucli-x.y.*.rpm) need administrator rights.
+# HP Array Configuration Utility CLI (hpacucli) need administrator rights.
 # Please add this line to /etc/sudoers :
 # --------------------------------------------------
 # nagios      ALL=NOPASSWD: /usr/sbin/hpacucli
 #
 # !!!!!!!!!!!!!!!!!!!
 #
-# NB: Please update the hpacucli to the current version (8.10)
+# NB: Please update the hpacucli to the current version (8.70)
 #
 # !!!!!!!!!!!!!!!!!!!
 #
@@ -39,6 +43,13 @@
 #   ./check_cciss -v
 # RAID OK:  Smart Array 6i in Slot 0 array A logicaldrive 1 (67.8 GB, RAID 1+0, OK)
 #           [Controller Status: OK  Cache Status: OK  Battery Status: OK]
+#
+# ./check_cciss.1.9 -v -p
+# RAID OK:  Smart Array 6i in Slot 0 (Embedded) array A logicaldrive 1 (33.9 GB, RAID 1, OK)
+#           physicaldrive 2:0 (port 2:id 0 , Parallel SCSI, 36.4 GB, OK)
+#           physicaldrive 2:1 (port 2:id 1 , Parallel SCSI, 36.4 GB, OK)
+#           physicaldrive 1:5 (port 1:id 5 , Parallel SCSI, 72.8 GB, OK, spare)
+#           [Controller Status: OK Cache Status: OK Battery/Capacitor Status: OK]
 #
 #   ./check_cciss
 # RAID OK
@@ -50,10 +61,20 @@
 #          A (failed) logicaldrive 1 (67.8 GB, 1+0, Interim Recovery Mode)
 #
 # RAID WARNING - HP Smart Array Rebuilding:  Smart Array 6i in Slot 0 array \
-#           A logicaldrive 1 (67.8 GB, 1+0, Rebuilding)
+#          A logicaldrive 1 (67.8 GB, 1+0, Rebuilding)
 #
 #
 # ChangeLog:
+#
+# 03/06/12 (1.9)
+#          - Increased debug verbosity
+#          - Added arguments to detect controller with HPSA driver (Hewlett Packard Smart Array) (-s)
+#          - Recognize required firmware upgrades
+#          - Don't confuse messages about a new fimrware with a chassis-error
+#          - Check physical drives for predicted failures
+#          - Added arguments to show detail for physical drives (-p)
+#          - Check the state of the cache (a dead battery will turn the cache off)
+#            (thanks to Casper Gielen and Kim Hagen)
 #
 # 10/06/08 (1.8)
 #          - Added support for chassis name (example MSA500)
@@ -63,27 +84,27 @@
 #
 # 07/12/08 (1.7)
 #          - Changed command argument support to use getopts and dropped the now unnecessary -N and -c options
-#            ( thanks to Reed Loden )
+#            (thanks to Reed Loden)
 #
 # 07/06/08 (1.6)
 #          - Added support for multiple arrays
-#            ( thanks to Reed Loden )
+#            (thanks to Reed Loden)
 #
 # 05/30/08 (1.5)
 #          - Added support for checking cache and battery status; added autodetection of slot number; corrected typo
-#            ( thanks to Reed Loden )
+#            (thanks to Reed Loden)
 #
 # 01/25/06 (1.4)
 #          - Changed "Rebuilding" grep with "Rebuild" for capture "Ready for Rebuild" status
-#            ( thanks to Loris A. )
+#            (thanks to Loris A.)
 #
 # 12/24/05 (1.3)
-#          - Added STATE_UNKNOWN when hpacucli command failed ( if sudo exit with error )
-#            ( thanks to Tim Hughes )
+#          - Added STATE_UNKNOWN when hpacucli command failed (if sudo exit with error)
+#            (thanks to Tim Hughes)
 #
 # 10/10/05 (1.2)
 #          - Now it's compatible with "Compaq Smart Array"
-#            ( suggested by Hans Engelen )
+#            (suggested by Hans Engelen)
 #
 # 10/07/05 (1.1)
 #          - Debug messages
@@ -96,10 +117,12 @@ PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
 
 PROGNAME=`basename $0`
 PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
-REVISION=`echo '$Revision: 1.8 $' | sed -e 's/[^0-9.]//g'`
+REVISION=`echo '$Revision: 1.9 $' | sed -e 's/[^0-9.]//g'`
+HPSA="0"
 DEBUG="0"
 VERBOSE="0"
 HPPROC="/proc/driver/cciss/cciss"
+HPSCSIPROC="/proc/scsi/scsi"
 COMPAQPROC="/proc/driver/cpqarray/ida"
 hpacucli="/usr/sbin/hpacucli"
 
@@ -107,25 +130,27 @@ hpacucli="/usr/sbin/hpacucli"
 
 print_usage() {
         echo ""
-        echo "Usage: $PROGNAME [-v] [-e <number>] [-E <name>] [-d]"
+        echo "Usage: $PROGNAME [-v] [-p] [-e <number>] [-E <name>] [-s] [-d]"
         echo "Usage: $PROGNAME [-h]"
         echo "Usage: $PROGNAME [-V]"
         echo ""
-        echo "  -v                   = output status and informations about RAID"
+        echo "  -v                   = show status and informations about RAID"
+        echo "  -p                   = show detail for physical drives"
         echo "  -e <number>          = exclude slot number"
         echo "  -E <name>            = exclude chassis name"
-        echo "  -d                   = use for debug ( command line mode )"
+        echo "  -s                   = detect controller with HPSA driver (Hewlett Packard Smart Array)"
+        echo "  -d                   = use for debug (command line mode)"
         echo "  -h                   = help information"
         echo "  -V                   = version information"
         echo ""
         echo " NOTE:"
         echo ""
-        echo " HP Array Configuration Utility CLI (hpacucli-x.y.*.rpm) need administrator rights."
+        echo " HP Array Configuration Utility CLI (hpacucli) need administrator rights."
         echo " Please add this line to /etc/sudoers"
         echo " --------------------------------------------------"
         echo " nagios      ALL=NOPASSWD: /usr/sbin/hpacucli"
         echo ""
-        echo " NB: Please update the hpacucli to the current version (8.10)"
+        echo " NB: Please update the hpacucli to the current version (8.70)"
 }
 
 print_help() {
@@ -139,12 +164,14 @@ print_help() {
         exit 0
 }
 
-while getopts "N:cvde:E:Vh" options
+while getopts "N:cvpsde:E:Vh" options
 do
     case $options in
       N)  ;;
       c)  ;;
       v)  VERBOSE=1;;
+      p)  PHYSICAL_DRIVE=1;;
+      s)  HPSA=1;;
       d)  DEBUG=1;;
       e)  EXCLUDE_SLOT=1
           excludeslot="$OPTARG";;
@@ -161,16 +188,22 @@ do
   esac
 done
 
+# Use HPSA driver (Hewlett Packard Smart Array)
+if [ "$HPSA" = "1" ]; then
+        COMPAQPROC="/proc/scsi/scsi"
+fi
+
+# Check if "HP Smart Array" is present
 raid=`cat $HPPROC* 2>&1`
 status=$?
 if [ "$DEBUG" = "1" ]; then
-        echo ${raid}
+        echo "### Check if \"HP Smart Array\" ($HPPROC) is present >>>\n"${raid}"\n"
 fi
 if test ${status} -eq 1; then
         raid=`cat $COMPAQPROC* 2>&1`
         status=$?
         if [ "$DEBUG" = "1" ]; then
-                echo ${raid}
+                echo "### Check if \"HP Smart Array\" ($COMPAQPROC) is present >>>\n"${raid}"\n"
         fi
         if test ${status} -eq 1; then
                 echo "RAID UNKNOWN - HP Smart Array not found"
@@ -178,30 +211,39 @@ if test ${status} -eq 1; then
         fi
 fi
 
+# Check if "HP Array Utility CLI" is present
 status=$?
 if [ "$DEBUG" = "1" ]; then
-        echo ${hpacucli}
+        echo "### Check if \"HP Array Utility CLI\" is present >>>\n"${hpacucli}"\n"
 fi
 if test ${status} -eq 1; then
         echo "RAID UNKNOWN - HP Array Utility CLI not found"
         exit $STATE_UNKNOWN
 fi
 
+# Check if "HP Controller" work correctly
 check=`sudo -u root $hpacucli controller all show status 2>&1`
 status=$?
+if [ "$DEBUG" = "1" ]; then
+        echo "### Check if \"HP Controller\" work correctly >>>\n"${check}"\n"
+fi
 if test ${status} -ne 0; then
         echo "RAID UNKNOWN - $hpacucli did not execute properly : "${check}
         exit $STATE_UNKNOWN
 fi
 
-
+# Get "Slot" & exclude slot needed
 if [ "$EXCLUDE_SLOT" = "1" ]; then
         slots=`echo ${check} | egrep -o "Slot \w" | awk '{print $NF}' | grep -v "$excludeslot"`
 else
         slots=`echo ${check} | egrep -o "Slot \w" | awk '{print $NF}'`
 fi
+if [ "$DEBUG" = "1" ]; then
+        echo "### Get \"Slot\" & exclude slot not needed >>>\n"${slots}"\n"
+fi
 for slot in $slots
 do
+        # Get "logicaldrive" for slot
         check2b=`sudo -u root $hpacucli controller slot=$slot logicaldrive all show 2>&1`
         status=$?
         if test ${status} -ne 0; then
@@ -209,15 +251,39 @@ do
                 exit $STATE_UNKNOWN
         fi
         check2="$check2$check2b"
+        if [ "$DEBUG" = "1" ]; then
+                echo "### Get \"logicaldrive\" for slot >>>\n"${check2b}"\n"
+        fi
+
+        # Get "physicaldrive" for slot
+        if [ "$PHYSICAL_DRIVE" = "1" -o "$DEBUG" = "1" ]; then
+                check2b=`sudo -u root $hpacucli controller slot=$slot physicaldrive all show 2>&1 | grep "physicaldrive"`
+        else
+                check2b=`sudo -u root $hpacucli controller slot=$slot physicaldrive all show 2>&1 | grep "physicaldrive" | grep "\(Failed\|Rebuilding\)" | echo ""`
+        fi
+        status=$?
+        if test ${status} -ne 0; then
+                echo "RAID UNKNOWN - $hpacucli did not execute properly : "${check2b}
+                exit $STATE_UNKNOWN
+        fi
+        check2="$check2$check2b"
+        if [ "$DEBUG" = "1" ]; then
+                echo "### Get \"physicaldrive\" for slot >>>\n"${check2b}"\n"
+        fi
 done
 
+# Get "Chassis" & exclude chassis not needed
 if [ "$EXCLUDE_CH" = "1" ]; then
-        chassisnames=`echo ${check} | egrep -o "in \w+" | egrep -v "Slot" | awk '{print $NF}' | grep -v "$excludech"`
+        chassisnames=`echo ${check} | grep -v "in a scenario of" | egrep -o "in \w+" | egrep -v "Slot" | awk '{print $NF}' | grep -v "$excludech"`
 else
-        chassisnames=`echo ${check} | egrep -o "in \w+" | egrep -v "Slot" | awk '{print $NF}'`
+        chassisnames=`echo ${check} | grep -v "in a scenario of" | egrep -o "in \w+" | egrep -v "Slot" | awk '{print $NF}'`
+fi
+if [ "$DEBUG" = "1" ]; then
+        echo "### Get \"Chassis\" & exclude chassis not needed >>>\n"${chassisnames}"\n"
 fi
 for chassisname in $chassisnames
 do
+        # Get "logicaldrive" for chassisname
         check2b=`sudo -u root $hpacucli controller chassisname="$chassisname" logicaldrive all show 2>&1`
         status=$?
         if test ${status} -ne 0; then
@@ -225,14 +291,39 @@ do
                 exit $STATE_UNKNOWN
         fi
         check2="$check2$check2b"
+        if [ "$DEBUG" = "1" ]; then
+                echo "### Get \"logicaldrive\" for chassisname >>>\n"${check2b}"\n"
+        fi
+
+        # Get "physicaldrive" for chassisname
+        check2b=`sudo -u root $hpacucli controller chassisname="$chassisname" physicaldrive all show 2>&1`
+        status=$?
+        if test ${status} -ne 0; then
+                echo "RAID UNKNOWN - $hpacucli did not execute properly : "${check2b}
+                exit $STATE_UNKNOWN
+        fi
+        check2="$check2$check2b"
+        if [ "$DEBUG" = "1" ]; then
+                echo "### Get \"physicaldrive\" for chassisname >>>\n"${check2b}"\n"
+        fi
 done
 
-if echo ${check} | egrep Failed >/dev/null; then
+# Check STATUS
+if [ "$DEBUG" = "1" ]; then
+       echo "### Check STATUS >>>"
+fi
+if echo ${check} | egrep "Cache Status: Temporarily Disabled" >/dev/null; then
+        echo "RAID WARNING - HP Smart Array Cache Disabled: "${check}
+        exit $STATE_WARNING
+elif echo ${check} | egrep Failed >/dev/null; then
         echo "RAID CRITICAL - HP Smart Array Failed: "${check} | egrep Failed
         exit $STATE_CRITICAL
 elif echo ${check} | egrep Disabled >/dev/null; then
         echo "RAID CRITICAL - HP Smart Array Problem: "${check} | egrep Disabled
         exit $STATE_CRITICAL
+elif echo ${check2} | egrep Failure >/dev/null; then
+        echo "RAID WARNING - Component Failure: "${check2} | egrep Failure
+        exit $STATE_WARNING
 elif echo ${check2} | egrep Rebuild >/dev/null; then
         echo "RAID WARNING - HP Smart Array Rebuilding: "${check2} | egrep Rebuild
         exit $STATE_WARNING
@@ -242,6 +333,9 @@ elif echo ${check2} | egrep Recover >/dev/null; then
 elif echo ${check2} | egrep Failed >/dev/null; then
         echo "RAID CRITICAL - HP Smart Array Failed: "${check2} | egrep Failed
         exit $STATE_CRITICAL
+elif echo ${check} | egrep FIRMWARE >/dev/null; then
+        echo "RAID WARNING - "${check}
+        exit $STATE_WARNING
 else
         if [ "$DEBUG" = "1" -o "$VERBOSE" = "1" ]; then
                 check3=`echo "${check}" | egrep Status`
