2012/04/04 (1.10)

diff --git a/check_cciss b/check_cciss
--- a/check_cciss
+++ b/check_cciss
@@ -44,7 +44,7 @@
 # RAID OK:  Smart Array 6i in Slot 0 array A logicaldrive 1 (67.8 GB, RAID 1+0, OK)
 #           [Controller Status: OK  Cache Status: OK  Battery Status: OK]
 #
-# ./check_cciss.1.9 -v -p
+# ./check_cciss -v -p
 # RAID OK:  Smart Array 6i in Slot 0 (Embedded) array A logicaldrive 1 (33.9 GB, RAID 1, OK)
 #           physicaldrive 2:0 (port 2:id 0 , Parallel SCSI, 36.4 GB, OK)
 #           physicaldrive 2:1 (port 2:id 1 , Parallel SCSI, 36.4 GB, OK)
@@ -66,7 +66,12 @@
 #
 # ChangeLog:
 #
-# 03/06/12 (1.9)
+# 2012/04/04 (1.10)
+#          - Critical states have priority over warning states
+#          - Fixed check physical drives for predicted failures without show detail (-p)
+#          - Fixed check physical drives for predicted failures in "chassis name" mode
+#
+# 2012/03/06 (1.9)
 #          - Increased debug verbosity
 #          - Added arguments to detect controller with HPSA driver (Hewlett Packard Smart Array) (-s)
 #          - Recognize required firmware upgrades
@@ -76,40 +81,40 @@
 #          - Check the state of the cache (a dead battery will turn the cache off)
 #            (thanks to Casper Gielen and Kim Hagen)
 #
-# 10/06/08 (1.8)
+# 2008/10/06 (1.8)
 #          - Added support for chassis name (example MSA500)
 #          - Added arguments to exclude slot number (-e <n>) and chassis name (-E <name>)
 #          - Added "Recovering" status reporting
 #          - Updated for hpacucli 8.10 version
 #
-# 07/12/08 (1.7)
+# 2008/07/12 (1.7)
 #          - Changed command argument support to use getopts and dropped the now unnecessary -N and -c options
 #            (thanks to Reed Loden)
 #
-# 07/06/08 (1.6)
+# 2008/07/06 (1.6)
 #          - Added support for multiple arrays
 #            (thanks to Reed Loden)
 #
-# 05/30/08 (1.5)
+# 2008/05/30 (1.5)
 #          - Added support for checking cache and battery status; added autodetection of slot number; corrected typo
 #            (thanks to Reed Loden)
 #
-# 01/25/06 (1.4)
+# 2006/01/25 (1.4)
 #          - Changed "Rebuilding" grep with "Rebuild" for capture "Ready for Rebuild" status
 #            (thanks to Loris A.)
 #
-# 12/24/05 (1.3)
+# 2005/12/24 (1.3)
 #          - Added STATE_UNKNOWN when hpacucli command failed (if sudo exit with error)
 #            (thanks to Tim Hughes)
 #
-# 10/10/05 (1.2)
+# 2005/10/10 (1.2)
 #          - Now it's compatible with "Compaq Smart Array"
 #            (suggested by Hans Engelen)
 #
-# 10/07/05 (1.1)
+# 2005/10/07 (1.1)
 #          - Debug messages
 #
-# 10/06/05 (1.0)
+# 2005/10/06 (1.0)
 #          - First production version
 # 
 
@@ -117,7 +122,7 @@ PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
 
 PROGNAME=`basename $0`
 PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
-REVISION=`echo '$Revision: 1.9 $' | sed -e 's/[^0-9.]//g'`
+REVISION=`echo '$Revision: 1.10 $' | sed -e 's/[^0-9.]//g'`
 HPSA="0"
 DEBUG="0"
 VERBOSE="0"
@@ -259,12 +264,14 @@ do
         if [ "$PHYSICAL_DRIVE" = "1" -o "$DEBUG" = "1" ]; then
                 check2b=`sudo -u root $hpacucli controller slot=$slot physicaldrive all show 2>&1 | grep "physicaldrive"`
         else
-                check2b=`sudo -u root $hpacucli controller slot=$slot physicaldrive all show 2>&1 | grep "physicaldrive" | grep "\(Failed\|Rebuilding\)" | echo ""`
+                check2b=`sudo -u root $hpacucli controller slot=$slot physicaldrive all show 2>&1 | grep "physicaldrive" | grep "\(Failure\|Failed\|Rebuilding\)"`
         fi
         status=$?
-        if test ${status} -ne 0; then
-                echo "RAID UNKNOWN - $hpacucli did not execute properly : "${check2b}
-                exit $STATE_UNKNOWN
+        if [ "$PHYSICAL_DRIVE" = "1" -o "$DEBUG" = "1" ]; then
+                if test ${status} -ne 0; then
+                        echo "RAID UNKNOWN - $hpacucli did not execute properly : "${check2b}
+                        exit $STATE_UNKNOWN
+                fi
         fi
         check2="$check2$check2b"
         if [ "$DEBUG" = "1" ]; then
@@ -296,11 +303,17 @@ do
         fi
 
         # Get "physicaldrive" for chassisname
-        check2b=`sudo -u root $hpacucli controller chassisname="$chassisname" physicaldrive all show 2>&1`
+        if [ "$PHYSICAL_DRIVE" = "1" -o "$DEBUG" = "1" ]; then
+                check2b=`sudo -u root $hpacucli controller chassisname="$chassisname" physicaldrive all show 2>&1 | grep "physicaldrive"`
+        else
+                check2b=`sudo -u root $hpacucli controller chassisname="$chassisname" physicaldrive all show 2>&1 | grep "physicaldrive" | grep "\(Failure\|Failed\|Rebuilding\)"`
+        fi
         status=$?
-        if test ${status} -ne 0; then
-                echo "RAID UNKNOWN - $hpacucli did not execute properly : "${check2b}
-                exit $STATE_UNKNOWN
+        if [ "$PHYSICAL_DRIVE" = "1" -o "$DEBUG" = "1" ]; then
+                if test ${status} -ne 0; then
+                        echo "RAID UNKNOWN - $hpacucli did not execute properly : "${check2b}
+                        exit $STATE_UNKNOWN
+                fi
         fi
         check2="$check2$check2b"
         if [ "$DEBUG" = "1" ]; then
@@ -312,14 +325,14 @@ done
 if [ "$DEBUG" = "1" ]; then
        echo "### Check STATUS >>>"
 fi
-if echo ${check} | egrep "Cache Status: Temporarily Disabled" >/dev/null; then
-        echo "RAID WARNING - HP Smart Array Cache Disabled: "${check}
-        exit $STATE_WARNING
-elif echo ${check} | egrep Failed >/dev/null; then
+if echo ${check} | egrep Failed >/dev/null; then
         echo "RAID CRITICAL - HP Smart Array Failed: "${check} | egrep Failed
         exit $STATE_CRITICAL
 elif echo ${check} | egrep Disabled >/dev/null; then
         echo "RAID CRITICAL - HP Smart Array Problem: "${check} | egrep Disabled
+        exit $STATE_CRITICAL
+elif echo ${check2} | egrep Failed >/dev/null; then
+        echo "RAID CRITICAL - HP Smart Array Failed: "${check2} | egrep Failed
         exit $STATE_CRITICAL
 elif echo ${check2} | egrep Failure >/dev/null; then
         echo "RAID WARNING - Component Failure: "${check2} | egrep Failure
@@ -330,9 +343,9 @@ elif echo ${check2} | egrep Rebuild >/dev/null; then
 elif echo ${check2} | egrep Recover >/dev/null; then
         echo "RAID WARNING - HP Smart Array Recovering: "${check2} | egrep Recover
         exit $STATE_WARNING
-elif echo ${check2} | egrep Failed >/dev/null; then
-        echo "RAID CRITICAL - HP Smart Array Failed: "${check2} | egrep Failed
-        exit $STATE_CRITICAL
+elif echo ${check} | egrep "Cache Status: Temporarily Disabled" >/dev/null; then
+        echo "RAID WARNING - HP Smart Array Cache Disabled: "${check}
+        exit $STATE_WARNING
 elif echo ${check} | egrep FIRMWARE >/dev/null; then
         echo "RAID WARNING - "${check}
         exit $STATE_WARNING
