2017/01/23 (1.13)

diff --git a/check_cciss b/check_cciss
--- a/check_cciss
+++ b/check_cciss
@@ -17,6 +17,7 @@
 #
 #  -v                   = show status and informations about RAID
 #  -p                   = show detail for physical drives
+#  -b			= exclude battery/capacitor/cache status check
 #  -e <number>          = exclude slot number
 #  -E <name>            = exclude chassis name
 #  -s                   = detect controller with HPSA driver (Hewlett Packard Smart Array)
@@ -30,7 +31,7 @@
 # HP Array Configuration Utility CLI (hpacucli) need administrator rights.
 # Please add this line to /etc/sudoers :
 # --------------------------------------------------
-# nagios      ALL=NOPASSWD: /usr/sbin/hpacucli
+# nagios      ALL=NOPASSWD: /usr/sbin/hpacucli, /usr/sbin/hpssacli
 #
 # !!!!!!!!!!!!!!!!!!!
 #
@@ -75,8 +76,22 @@
 #          physicaldrive 1:0 (port 1:id 0 , Parallel SCSI, 36.4 GB, Rebuilding) \
 #          physicaldrive 1:1 (port 1:id 1 , Parallel SCSI, 36.4 GB, OK)
 #
+# ./check_cciss -v -b
+# ----------------
+#
+# RAID OK:  Smart Array 6i in Slot 0 (Embedded) array A logicaldrive 1 (33.9 GB, RAID 1, OK) [Controller Status: OK]
+#
+#  [insted of]
+# RAID CRITICAL - HP Smart Array Failed:  Smart Array 6i in Slot 0 (Embedded) \
+#                 Controller Status: OK Cache Status: Temporarily Disabled \
+#                 Battery/Capacitor Status: Failed (Replace Batteries/Capacitors)
+#
 #
 # ChangeLog:
+#
+# 2017/01/23 (1.13)
+#          - Support hpssacli in addition to hpacucli
+#          - Added cli flag '-b' to exclude battery/capacitor/cache status check
 #
 # 2013/11/20 (1.12)
 #          - Auto-detect the HPSA driver (tested with DL360/380 G6 with Ubuntu 12.04 LTS)
@@ -140,7 +155,7 @@ PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
 
 PROGNAME=`basename $0`
 PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
-REVISION=`echo '$Revision: 1.12 $' | sed -e 's/[^0-9.]//g'`
+REVISION=`echo '$Revision: 1.13 $' | sed -e 's/[^0-9.]//g'`
 HPSA="0"
 DEBUG="0"
 VERBOSE="0"
@@ -153,7 +168,7 @@ hpacucli="/usr/sbin/hpacucli"
 
 print_usage() {
         echo ""
-        echo "Usage: $PROGNAME [-v] [-p] [-e <number>] [-E <name>] [-s] [-d]"
+        echo "Usage: $PROGNAME [-v] [-p] [-e <number>] [-E <name>] [-b] [-s] [-d]"
         echo "Usage: $PROGNAME [-h]"
         echo "Usage: $PROGNAME [-V]"
         echo ""
@@ -161,6 +176,7 @@ print_usage() {
         echo "  -p                   = show detail for physical drives"
         echo "  -e <number>          = exclude slot number"
         echo "  -E <name>            = exclude chassis name"
+        echo "  -b                   = exclude battery/capacitor/cache status check"
         echo "  -s                   = detect controller with HPSA driver (Hewlett Packard Smart Array)"
         echo "  -d                   = use for debug (command line mode)"
         echo "  -h                   = help information"
@@ -168,12 +184,12 @@ print_usage() {
         echo ""
         echo " NOTE:"
         echo ""
-        echo " HP Array Configuration Utility CLI (hpacucli) need administrator rights."
+        echo " HP Array Configuration Utility CLI (hpacucli / hpssacli) need administrator rights."
         echo " Please add this line to /etc/sudoers"
         echo " --------------------------------------------------"
-        echo " nagios      ALL=NOPASSWD: /usr/sbin/hpacucli"
+        echo " nagios      ALL=NOPASSWD: /usr/sbin/hpacucli, /usr/sbin/hpssacli"
         echo ""
-        echo " NB: Please update the hpacucli to the current version (8.70)"
+        echo " NB: Please update the hpacucli to the current version (today 9.40) or >8.70"
 }
 
 print_help() {
@@ -187,7 +203,7 @@ print_help() {
         exit 0
 }
 
-while getopts "N:cvpsde:E:Vh" options
+while getopts "N:cvpbsde:E:Vh" options
 do
     case $options in
       N)  ;;
@@ -200,6 +216,7 @@ do
           excludeslot="$OPTARG";;
       E)  EXCLUDE_CH=1
           excludech="$OPTARG";;
+      b)  EXCLUDE_BATTERY=1;;
       V)  print_revision $PROGNAME $REVISION
           exit 0;;
       h)  print_help
@@ -235,13 +252,13 @@ if test ${status} -eq 1; then
 fi
 
 # Check if "HP Array Utility CLI" is present
-status=$?
-if [ "$DEBUG" = "1" ]; then
-        echo "### Check if \"HP Array Utility CLI\" is present >>>\n"${hpacucli}"\n"
-fi
-if test ${status} -eq 1; then
-        echo "RAID UNKNOWN - HP Array Utility CLI not found"
-        exit $STATE_UNKNOWN
+if [ ! -x $hpacucli ]; then
+        if [ -x /usr/sbin/hpssacli ]; then
+                hpacucli='/usr/sbin/hpssacli'
+        else
+                echo "ERROR: hpacucli or hpssacli tools should be installed!"
+                exit $STATE_UNKNOWN
+        fi
 fi
 
 # Check if "HP Controller" work correctly
@@ -343,6 +360,13 @@ done
 if [ "$DEBUG" = "1" ]; then
        echo "### Check STATUS >>>"
 fi
+
+# Omit battery/capacitor/cache status check if requested
+if [ "$EXCLUDE_BATTERY" = "1" ]; then
+       check=`echo "$check" | grep -v 'Battery/Capacitor Status: Failed (Replace Batteries/Capacitors)'`
+       check=`echo "$check" | grep -v 'Cache Status: Temporarily Disabled'`
+fi
+
 if echo ${check} | egrep Failed >/dev/null; then
         echo "RAID CRITICAL - HP Smart Array Failed: "${check} | egrep Failed
         exit $STATE_CRITICAL
